host: '192.168.150.11'
#host: '192.168.43.158' #nacos的IP地址每次换网都得修改
port: 8848
namespace: 'c6bff0ef-3e55-4fa8-931a-8afe66911f0e'
dataId: 'product.json'
group:  'dev'
timeoutMs:  5000
notLoadCacheAtStart: true
logDir: 'nacos/log'
cacheDir: 'nacos/cache'
logLevel: 'debug'
