global:
  scrape_interval: 15s # 设置Prometheus抓取指标的时间间隔

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["192.168.150.11:9090"]
  - job_name: 'product_srv'
    static_configs:
      - targets: ["192.168.150.11:9091"]
